theme: jekyll-theme-cayman
title: Ayudantía 13
title-icon: fas fa-code
author:
  name: Nicolás Mendicoa
  email: nmendicoa@uc.cl  
description: "Introducción a Ciencia de Datos, 2022-2"
pub_year: 2021
markdown: kramdown
